# https://github.com/bjw-s/helm-charts/tree/main/charts/library/common
image:
  repository: tsightler/ring-mqtt
  tag: 5.0.5
  pullPolicy: IfNotPresent
  
controller:
  revisionHistoryLimit: 1

service:
  main:
    ports:
      http:
        enabled: false
      rtsp:
        port: 8554
        protocol: TCP
        primary: true

persistence:
  data:
    enabled: true
    storageClass: argo-zfspv-fast
    size: 50Gi
    accessMode: ReadWriteOnce
    retain: true
