{{- range .Values.global.applicationSets }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "argo-{{ . }}"
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: "{{ $.Values.global.repo }}"
      revision: "{{ $.Values.global.branch }}"
      directories:
      - path: "{{ . }}/*"
  template:
    metadata:
      name: "{{`{{ path.basename }}`}}"
    spec:
      project: argocd-scale
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        repoURL: "{{ $.Values.global.repo }}"
        targetRevision: "{{ $.Values.global.branch }}"
        path: "{{`{{ path }}`}}"
        helm:
          valueFiles:
            - values.yaml
            - ../../globalValues.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: "argo-{{ . }}"
---
{{- end}}