apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}-http
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hydra.brushfi.re`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}
          port: http
  tls:
    secretName: {{ .Chart.Name }}-tls
    options:
      name: {{ .Chart.Name }}-tlsoption
      namespace: {{ .Release.Namespace }}
